### ISSUE TITLE
Add a (placeholder) analysis section

### ISSUE THREAD

**Issue by marisaaquilina** [builtbyspec/app-cookiecutter#3]
Add a section for a statistical analysis. Include a Plotly graph with placeholder analysis text below it. Style with css.

Note: refer to Plotly docs if necessary. For the text section, it would be nice if this can be pulled from a JSON file as opposed to a static Python string.

**Comment by TheCruzControll** [comment]
@marisaaquilina Finished Draft. Added sample data with a graph and prose. Lmk if theres anything missing.
